pr: none
trigger: none

stages:
  - stage: experimental
    displayName: Experimental
    jobs:
      - job: env
        displayName: Test Job
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              echo "Hello World!"
            name: "StateHello"
            displayName: "Say Hello World"
            condition: always()
  - stage: setup
    displayName: Setup
    jobs:
      - job: env
        displayName: Setup
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              echo "Setting up environment"
              echo "##vso[task.setvariable variable=npmVersion;isOutput=true]$(make npm-version)"
              go version
            name: "SetEnvVars"
            displayName: "Set Environment Variables"
            condition: always()
  - template: cilium/cilium-overlay-load-test-template.yaml
    parameters:
      name: cilium
      clusterType: cilium-overlay-up
      clusterName: "cilium-overlay"
      nodeCount: ${CILIUM_NODE_COUNT}
      vmSize: "Standard_DS4_v2"
      dependsOn: setup
  - template: singletenancy/windows-cni-load-test-template.yaml
    parameters:
      name: win_cniv1
      clusterType: "windows-cniv1-up"
      clusterName: "win-cniv1"
      nodeCount: ${WINDOWS_NODE_COUNT}
      vmSize: Standard_B2ms
      dependsOn: setup
      windowsVMSize: ${WINDOWS_VM_SKU}
      os: windows
      cni: cniv1
